package com.smallchill.platform.model;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2016-09-14 11:35:10
 */
@Table(name = "tb_report")
@BindID(name = "ID")
@SuppressWarnings("serial")
public class Report extends BaseModel {

}
