package com.smallchill.platform.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.platform.model.Report;

/**
 * Generated by yesong.
 * 2016-09-14 11:35:10
 */
public interface ReportService extends IService<Report>{

}
