package com.smallchill.platform.service.impl;

import com.smallchill.platform.model.Report;
import com.smallchill.platform.service.ReportService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

/**
 * Generated by yesong.
 * 2016-09-14 11:35:10
 */
@Service
public class ReportServiceImpl extends BaseService<Report> implements ReportService {

}
